apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-pvc
  namespace: retail-store
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  volumeName: carts-pv